services:
    Marfatech\Bundle\SupervisorBundle\Service\SupervisorAnnotationService:
        class: Marfatech\Bundle\SupervisorBundle\Service\SupervisorAnnotationService
        arguments:
            - '@annotation_reader'
            - '%marfatech_supervisor.config%'
        calls:
            - ['setLogger', ['@?logger']]

    Marfatech\Bundle\SupervisorBundle\Service\SupervisorSourceService:
        class: Marfatech\Bundle\SupervisorBundle\Service\SupervisorSourceService
        arguments:
            - '@Marfatech\Bundle\SupervisorBundle\Service\SupervisorAnnotationService'
            - '%kernel.project_dir%'
            - '%marfatech_supervisor.config%'
        calls:
            - ['setLogger', ['@?logger']]

    Marfatech\Bundle\SupervisorBundle\Command\DumpCommand:
        class: Marfatech\Bundle\SupervisorBundle\Command\DumpCommand
        calls:
            - ['injectDependency', ['@Marfatech\Bundle\SupervisorBundle\Service\SupervisorAnnotationService', '@Marfatech\Bundle\SupervisorBundle\Service\SupervisorSourceService']]
        tags:
            - { name: console.command }
